var nodemailer = require('nodemailer');
const configs = require('./configs');


var transport = nodemailer.createTransport({
    host: configs.MAIL_HOST,
    port: configs.MAIL_PORT,
    auth: {
        user: configs.MAIL_USER, //example of generated by Mailtrap 
        pass: configs.MAIL_PASS //example of generated by Mailtrap 
    }
});


const imageLinkTest = `https://t4.ftcdn.net/jpg/03/03/62/45/240_F_303624505_u0bFT1Rnoj8CMUSs8wMCwoKlnWlh5Jiq.jpg`;
module.exports = {
    send: async function (email, message) {
        await transport.sendMail({
            from: 'iamasystemadmin@gmail.com',
            to: email,
            subject: 'RESET PASSWORD',
            html: `<a href='/authen/resetPassword/${message}'>bam vao day de doi mat khau</a>
                <img src="${imageLinkTest}" alt="Test Image"/>`,
        })
    },
}